version: "3"

services:
  mongodb-6.0:
    image: mongo:6.0
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
    volumes:
      - "~/development/docker/volumes/mongodb-6.0/data/db:/data/db"
    ports:
      - "27017:27017"
